services:
  postgres:
    image: postgres:15-alpine
    container_name: config-service-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_DB:-config_service}
      POSTGRES_USER: ${DATABASE_USER:-config_user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-config_password}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - config-service-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-config_user} -d ${DATABASE_DB:-config_service}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  config-service-network:
    driver: bridge
