version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: configservice-db
    environment:
      POSTGRES_DB: configservice
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./svc/migrations:/docker-entrypoint-initdb.d/migrations
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d configservice"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: